					<!-- BREAK POINT 1 -->
					</td>
					<td width="4" height="100%">
						<table width="10" height="100%" border="0" cellpadding="0" cellspacing="0">
							<tr>
								<td width="10" height="7">
									<img src="images/timesheet_face_06.gif" width="10" height="7" alt="" /></td>
							</tr>
							<tr>
								<td width="10">
									<img src="images/timesheet_face_08.gif" width="10" height="100%" alt="" /></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td width="100%" height="100%">
			<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
				<tr height="100%">
					<td width="13" height="100%">
						<table width="13" height="100%" border="0" cellpadding="0" cellspacing="0">
							<tr>
								<td width="13" height="19">
									<img src="images/timesheet_face_09.gif" width="13" height="19" /></td>
							</tr>
							<tr>
								<td width="13" height="100%">
									<img src="images/timesheet_face_15.gif" width="13" height="100%" /></td>			
							</tr>
							<tr>
								<td width="13" height="6">
									<img src="images/timesheet_face_17.gif" width="13" height="6" alt="" /></td>
							</tr>
						</table>
					</td>
					<td width="100%" height="100%" class="faceBackground">
						<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">
							<tr height="17">
								<td width="5" height="17">
									<img src="images/timesheet_face_10.gif" width="5" height="17" alt="" /></td>
								<td width="100%" height="17">
									<img src="images/timesheet_face_11.gif" width="100%" height="17" alt="" /></td>								
								<td width="4" height="17">
									<img src="images/timesheet_face_12.gif" width="4" height="17" alt="" /></td>
							</tr>
							<tr height="100%">
								<td colspan="3" width="100%" height="100%" class="faceBackground">
								<!-- BREAK POINT 2 -->
								